# Generated by Django 4.2.11 on 2024-04-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_eduitem_sportitem_newsitem_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EduItem',
        ),
    ]
