# Generated by Django 4.2.11 on 2024-04-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_delete_eduitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_link', models.URLField()),
                ('link', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
