# Generated by Django 4.2.11 on 2024-04-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0006_delete_eduitem_delete_sportitem_newsitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
