# Generated by Django 4.2.11 on 2024-04-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0009_newsitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
